name: Anchore Security Scan for UBI

on:
    release:
        types: [published]
    schedule:
        - cron: "0 8 * * 1"
    workflow_dispatch:

jobs:
    anchore:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: Build UBI container
              uses: docker/build-push-action@v2
              with:
                  context: ./extras/docker
                  tags: localbuild/ubi:latest
                  push: false
                  load: true
                  build-args: |
                      BUILDER=registry.access.redhat.com/ubi8/nodejs-14
                      DISTRO=registry.access.redhat.com/ubi8/nodejs-14-minimal
                      PACKAGE_MANAGER=yum
                      USER=1001
            - name: Security Scan for UBI Image
              uses: anchore/scan-action@v3
              id: scan-ubi
              if: always()
              with:
                  image: "localbuild/ubi:latest"
                  acs-report-enable: true
                  severity-cutoff: critical
            - name: Upload UBI Report
              uses: actions/upload-artifact@v2
              if: always()
              with:
                  name: node-slim-report
                  path: ${{ steps.scan-ubi.outputs.sarif }}
